FTVECTORSRCS = ftVector.cpp
FTMAPSRCS = ftMap.cpp
STDVECTORSRCS = stdVector.cpp
STDMAPSRCS = stdMap.cpp

CC = c++
CPPFLAGS = -std=c++98
LDFLAGS = -fsanitize=address -g3
FTVECTORNAME = ftVector
FTMAPNAME = ftMap
STDVECTORNAME = stdVector
STDMAPNAME = stdMap

all: $(FTVECTORNAME)  $(FTMAPNAME) $(STDVECTORNAME)  $(STDMAPNAME) 

$(FTVECTORNAME): $(FTVECTORSRCS)
	$(CC) $(CPPFLAGS) $(FTVECTORSRCS) -o $(FTVECTORNAME)

$(FTMAPNAME): $(FTMAPSRCS)
	$(CC) $(LDFLAGS) $(CPPFLAGS) $(FTMAPSRCS) -o $(FTMAPNAME)

$(STDVECTORNAME): $(STDVECTORSRCS)
	$(CC) $(CPPFLAGS) $(STDVECTORSRCS) -o $(STDVECTORNAME)

$(STDMAPNAME): $(STDMAPSRCS)
	$(CC) $(LDFLAGS) $(CPPFLAGS) $(STDMAPSRCS) -o $(STDMAPNAME)

runm:
	./$(FTMAPNAME)
	./$(STDMAPNAME)

runv:
	./$(FTVECTORNAME)
	./$(STDVECTORNAME)

clean:
	rm -f $(FTMAPNAME) $(STDMAPNAME) $(FTVECTORNAME) $(STDVECTORNAME)

fclean: clean

re: fclean all